### ISSUE TITLE
click method creates a step in the report

### ISSUE THREAD

**Issue by YaronWhite** [Perfecto-Quantum/Quantum-Starter-Kit#26]
The click method click("save.contact"); is a very useful short way to click on elements but ..... it cannot be used since it creates a seperate step in the report.

**Comment by kulin24** [comment]
The click method was not designed to be used directly as a method as if you will go into the implementation of this method you will find that these are actually step definitions and there are internal hooks in QAF with these steps. So we cannot fix this.
