### ISSUE TITLE
Priority configuration in Testng.xml

### ISSUE THREAD

**Issue by myProwess** [Perfecto-Quantum/Quantum-Starter-Kit#30]
I am using Quantum Framework. I created annotation for scenarios and feature files. However i need to give priority in testng.xml file to my annotations while running as testng suite.

But now it is running as whichever annotation reads first it is executing in the order

Please help me I need to resolve at the earliest.

**Comment by kulin24** [comment]
In testNG you can give priority with following syntax:
`package com.guru.testngannotations;
import org.testng.annotations.Test;

public class TestNG_Priority_Annotations {

    @Test(priority=6)
    public void c_method(){
    System.out.println("I'm in method C");
    }
    @Test(priority=9)
    public void b_method(){
    System.out.println("I'm in method B");
    }
    @Test(priority=6)
    public void a_method(){
    System.out.println("I'm in method A");
    }
    @Test(priority=0)
    public void e_method(){
    System.out.println("I'm in method E");
    }
    @Test(priority=3)
    public void d_method(){
    System.out.println("I'm in method D");
    }

}`

In our gherkin scenarios you can give priority using the examples:

 @WebDDxml
  Scenario Outline: Search Keyword XML Data
    Given I am on Google Search Page
    When I search for "<searchKey>"
    Then it should have "<searchResult>" in search results

    #xml file must be in directory listed in env.resources property
    Examples: {'key' : 'demo.websearch.dataset', 'priority':1}


You cannot prioritize the tags name that you are including that is a limitation from testNG.
