### ISSUE TITLE
Multiple definitions found for `I start application by name `

### ISSUE THREAD

**Issue by Shanehess** [Perfecto-Quantum/Quantum-Starter-Kit#33]
When I grab the starter project kit from git, I am getting an error that I have multiple definitions found for I start application by name. I haven't added any steps. This is just the base import from maven and the sample example for starting calculator.

**Comment by kulin24** [comment]
Is this issue still reproducible?
For me, it is working as expected. 

We have seen that is there are multiple starter kit projects in your workspace then the eclipse get confused with the step definition.
