### ISSUE TITLE
Defining application.properties file

### ISSUE THREAD

**Issue by altonch** [Perfecto-Quantum/Quantum-Starter-Kit#37]
Currently we have the application properties file and the related values in our documentation here.

It does not show the details of the features. For example:

installApp

This does not define the parameters for instrumentation, both web and sensor. We need the documentation updated to show the correct code for the application.properties file, which includes the exact code writing for each function and all the related parameters, including how it looks in Quantum.

Support gets these questions A LOT.

**Comment by kulin24** [comment]
Thanks for the feedback. We will update the documentation on this.
