### ISSUE TITLE
driver chrome ,how to simulate ipad with option?

### ISSUE THREAD

**Issue by hp-web** [Perfecto-Quantum/Quantum-Starter-Kit#46]
like this :
but,how can i implement this with Quantum-Starter-Kit   ?. DriverUtils.getDriver();?   how to use it  ?
        Map<String, Object> deviceMetrics = new HashMap<String, Object>();

        //设置屏幕大小、像素
        deviceMetrics.put("width", 480);
        deviceMetrics.put("height", 720);
        deviceMetrics.put("pixelRatio", 3.0);

        Map<String, Object> mobileEmulation = new HashMap<String, Object>();
        mobileEmulation.put("deviceMetrics", deviceMetrics);

        //设置要模拟的手机标识
        mobileEmulation.put("userAgent",
                "Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1");

        //声明ChromeOptions，主要是给chrome设置参数
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setExperimentalOption("mobileEmulation", mobileEmulation);

        //设置驱动位置
        System.setProperty("webdriver.chrome.driver", "D:\\tools\\chromedriver_win32\\chromedriver.exe");
        WebDriver driver = new ChromeDriver(chromeOptions);

**Comment by ksitwala-perfecto** [comment]
`<parameter name="chrome.additional.capabilities" value="{'chromeOptions':{'mobileEmulation':{'deviceName':'iPad'}}}" />`

You can mention the above capability parameter and that should emulate the iPad on Chrome browser. Please note that this chrome emulation is not an effective way of testing the iOS safari browser. The reason being that the underlying browser is the Chrome and Safari has different technology involved in it. Therefore, it is recommended to test on real iPad Safari browser to do effective testing.
