### ISSUE TITLE
how to re-try test case use this framework

### ISSUE THREAD

**Issue by hp-web** [Perfecto-Quantum/Quantum-Starter-Kit#47]
hi all,
i want to re-try test case whitch run failed first time ,But i don't want to excute all case again,just run failed cases again .  what should i do ?  thanks you very much.

**Comment by ksitwala-perfecto** [comment]
@hp-web - You can run all hte failed test cases except the ones that have failed with Assertions using the key retry.count=1 in application properties.
https://stackoverflow.com/questions/49061194/how-to-run-only-failed-test-cases-in-qaf

Furthermore, the framework also supports custom retry analyser that will allow you to even filter failures that are to be re-executed.
