### ISSUE TITLE
WFA-401-0000 - Not authorized Issue

### ISSUE THREAD

**Issue by rokuamit01** [Perfecto-Quantum/Quantum-Starter-Kit#50]
While using latest quantum framework version, I am getting following error:

com.qmetry.qaf.automation.core.AutomationError: Unable to Create Driver Instance com.perfecto.wfa.server.errors.ErrorCodeException: WFA-401-0000 - Not authorized  Details: 'Failed to authenticate session.'

I have tried following solution -> https://developers.perfectomobile.com/display/TT/Troubleshooting+%28WEB%29+-+WFA-401-0000+-+Not+authorized

but nothing worked out so far.

I am n IntelliJ 2019.3.2
Java 1.8
Maven 3.6

I am using organization proxies for connection. Everything was working in previous version, am I missing anything?

**Comment by davidreedme** [comment]
Howdy, @rokuamit01. Are you using a security token? Which cloud are you plugged into? When you say previous version, which number does that mean?

**Comment by ksitwala-perfecto** [comment]
Hi @rokuamit01  - Based on the error it seems that your authentication was unsuccessful and it might be because of a very old security token. Please create a new security token and then retry to create the driver. That should fix your issue.
