### ISSUE TITLE
Create Samples

### ISSUE THREAD

**Issue by tal-abraham** [Perfecto-Quantum/Quantum-Starter-Kit#9]
Samples - Have 4 different samples :
 - Simple web example
 - Web example with data driven
 - Simple native example
 - Simple native example with data driven Native examples should work both on android and ios.

Each sample name should be self explanatory, so user will understand what does the sample shows by its name

**Comment by sumitv-007** [comment]
We need to have a sample of one script executing on both (Desktop web & mobile) as an example too. 

Also in the link below the Pre-Defined steps are not mentioned for Web separately.
https://github.com/Project-Quantum/Quantum-Starter-Kit/wiki/Perfecto%20predefined%20steps

I understand that a few of the “application” steps can be used for Web too, but it does not come out clearly / explicitly. Maybe just one more column (can be used for Desktop Web – with yes/no) would also suffice.
